layout:
  defaultGroup: custom
  groups:
    - name: content
      apps:
        - name: pages-app
        - name: dam-app
        - name: stories
        - name: faqs-app
    - name: football
      label: Football
      apps:
        - name: banners-app
        - name: posts-app
        - name: headers-app
        - name: footers-app
  rows:
    - name: one
      groups:
        content: content
        marketing: marketing
        football: football
