services:
  # docker compose up --build builder
  builder:
    image: maven:3.8.6-openjdk-11
    container_name: builder
    working_dir: /usr/src/app
    volumes:
      - ./custom-project-minimal:/usr/src/app
      - ~/.m2:/root/.m2
    command: mvn clean install

  server:
    image: tomcat:9.0-jdk11
    container_name: server
    ports:
      - "8081:8080"
    volumes:
      - ./custom-project-minimal/custom-project-minimal-webapp/target/custom-project-minimal-webapp-1.0-SNAPSHOT.war:/usr/local/tomcat/webapps/ROOT.war
      - ./logs:/usr/local/tomcat/logs
      - /Users/kobbie.tran/tuanta/magnolia/server-mvn/light-modules:/app/light-modules
      - /Users/kobbie.tran/tuanta/magnolia/server-mvn/repositories:/app/repositories
    environment:
      - magnolia.superuser.enabled=true
      - magnolia.superuser.password=superuser
      - MAGNOLIA_RESOURCES_HOME=/app/light-modules
      - MAGNOLIA_REPOSITORIES_HOME=/app/repositories
      - MAGNOLIA_PROFILE=develop
    depends_on:
      - builder
