# This file is intended for use in the local development environment only.
# Light modules directory is ./src/main/magnolia
magnolia.resources.dir=${MAGNOLIA_RESOURCES_HOME}

# Repository directory is ./repositories so it doesn't get wiped by mvn clean
magnolia.repositories.home=${MAGNOLIA_REPOSITORIES_HOME}

# Switch to false to enhance the performance of the javascript generation and similar
magnolia.develop=true

# Sticker indicating the active profile in the Admin Central UI
magnolia.ui.sticker.environment=${MAGNOLIA_PROFILE}
magnolia.ui.sticker.color=red
magnolia.yaml.maxAliasesForCollections=100
magnolia.applauncher.config.compatibility=false
