# https://docs.magnolia-cms.com/magnolia-sso/#_configuring_via_yaml
# https://manage.auth0.com/dashboard/jp/chasingx/applications/8OsZsYeUziz4PjcBaB40n0pR8z7Rpg1W/settings

callbackUrl: /.auth
authorizationGenerators:
  - name: fixedRoleAuthorization
    fixed:
      targetRoles:
        - superuser
  - name: groupsAuthorization
    groups:
      targetProperty: magnolia-groups
      mappings:
        - name: magnolia-users
          targetRoles:
            - developer
            - editor

clients:
  oidc.id: 8OsZsYeUziz4PjcBaB40n0pR8z7Rpg1W
  oidc.secret: $OIDC_CLIENT_SECRET
  oidc.clientAuthenticationMethod: client_secret_basic
  oidc.scope: openid profile email
  oidc.discoveryUri: https://chasingx.jp.auth0.com/.well-known/openid-configuration
  #oidc.authorizationGenerators: fixedRoleAuthorization
  oidc.authorizationGenerators: groupsAuthorization
  oidc.preferredJwsAlgorithm: RS256

userFieldMappings:
  name: email
  removeEmailDomainFromUserName: true
  fullName: name
  email: email
  language: locale
