# https://docs.magnolia-cms.com/magnolia-sso/#_configuring_via_yaml
# https://manage.auth0.com/dashboard/jp/chasingx/applications/8OsZsYeUziz4PjcBaB40n0pR8z7Rpg1W/settings

callbackUrl: /.auth
authorizationGenerators:
  - name: fixedRoleAuthorization
    fixed:
      targetRoles:
        - superuser
  # - name: groupsAuthorization
  #   groups:
  #     targetProperty: groups
  #     mappings:
  #       - name: magnolia-users
  #         targetGroups:
  #           - publishers
  #         targetRoles:
  #           - superuser

clients:
  oidc.id: 8OsZsYeUziz4PjcBaB40n0pR8z7Rpg1W
  oidc.secret: A7i30uxePuUpS2Yj6K-wCVogN4Dx5cQzaaPSQUs3AvTlFSzKKYRmvzPxRd1vi5nl
  oidc.clientAuthenticationMethod: client_secret_basic
  oidc.scope: openid profile email
  oidc.discoveryUri: https://chasingx.jp.auth0.com/.well-known/openid-configuration
  oidc.authorizationGenerators: fixedRoleAuthorization
  oidc.preferredJwsAlgorithm: RS256

userFieldMappings:
  name: email
  removeEmailDomainFromUserName: true
  fullName: name
  email: email
  language: locale
